/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BookFlightRouteImport } from './routes/book-flight'
import { Route as CarsRouteImport } from './routes/cars'
import { Route as DealsRouteImport } from './routes/deals'
import { Route as FlightsRouteImport } from './routes/flights'
import { Route as HostRouteImport } from './routes/host'
import { Route as MoreRouteImport } from './routes/more'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as SearchRouteImport } from './routes/search'
import { Route as StaysRouteImport } from './routes/stays'
import { Route as SupportRouteImport } from './routes/support'
import { Route as TransfersRouteImport } from './routes/transfers'
import { Route as TripsRouteImport } from './routes/trips'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as ActivitiesIndexRouteImport } from './routes/activities.index'
import { Route as ActivitiesSlugRouteImport } from './routes/activities.$slug'
import { Route as BookSlugRouteImport } from './routes/book.$slug'
import { Route as BookingReferenceRouteImport } from './routes/booking.$reference'
import { Route as ListingSlugRouteImport } from './routes/listing.$slug'
import { Route as OrderReferenceRouteImport } from './routes/order.$reference'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BookFlightRoute = BookFlightRouteImport.update({
  id: '/book-flight',
  path: '/book-flight',
  getParentRoute: () => rootRouteImport,
} as any)
const CarsRoute = CarsRouteImport.update({
  id: '/cars',
  path: '/cars',
  getParentRoute: () => rootRouteImport,
} as any)
const DealsRoute = DealsRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => rootRouteImport,
} as any)
const FlightsRoute = FlightsRouteImport.update({
  id: '/flights',
  path: '/flights',
  getParentRoute: () => rootRouteImport,
} as any)
const HostRoute = HostRouteImport.update({
  id: '/host',
  path: '/host',
  getParentRoute: () => rootRouteImport,
} as any)
const MoreRoute = MoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const StaysRoute = StaysRouteImport.update({
  id: '/stays',
  path: '/stays',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const TransfersRoute = TransfersRouteImport.update({
  id: '/transfers',
  path: '/transfers',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsRoute = TripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitiesIndexRoute = ActivitiesIndexRouteImport.update({
  id: '/activities/',
  path: '/activities/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitiesSlugRoute = ActivitiesSlugRouteImport.update({
  id: '/activities/$slug',
  path: '/activities/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BookSlugRoute = BookSlugRouteImport.update({
  id: '/book/$slug',
  path: '/book/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingReferenceRoute = BookingReferenceRouteImport.update({
  id: '/booking/$reference',
  path: '/booking/$reference',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingSlugRoute = ListingSlugRouteImport.update({
  id: '/listing/$slug',
  path: '/listing/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderReferenceRoute = OrderReferenceRouteImport.update({
  id: '/order/$reference',
  path: '/order/$reference',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/book-flight': typeof BookFlightRoute
  '/cars': typeof CarsRoute
  '/deals': typeof DealsRoute
  '/flights': typeof FlightsRoute
  '/host': typeof HostRoute
  '/more': typeof MoreRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/stays': typeof StaysRoute
  '/support': typeof SupportRoute
  '/transfers': typeof TransfersRoute
  '/trips': typeof TripsRoute
  '/welcome': typeof WelcomeRoute
  '/activities/$slug': typeof ActivitiesSlugRoute
  '/book/$slug': typeof BookSlugRoute
  '/booking/$reference': typeof BookingReferenceRoute
  '/listing/$slug': typeof ListingSlugRoute
  '/order/$reference': typeof OrderReferenceRoute
  '/activities/': typeof ActivitiesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/book-flight': typeof BookFlightRoute
  '/cars': typeof CarsRoute
  '/deals': typeof DealsRoute
  '/flights': typeof FlightsRoute
  '/host': typeof HostRoute
  '/more': typeof MoreRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/stays': typeof StaysRoute
  '/support': typeof SupportRoute
  '/transfers': typeof TransfersRoute
  '/trips': typeof TripsRoute
  '/welcome': typeof WelcomeRoute
  '/activities/$slug': typeof ActivitiesSlugRoute
  '/book/$slug': typeof BookSlugRoute
  '/booking/$reference': typeof BookingReferenceRoute
  '/listing/$slug': typeof ListingSlugRoute
  '/order/$reference': typeof OrderReferenceRoute
  '/activities': typeof ActivitiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/book-flight': typeof BookFlightRoute
  '/cars': typeof CarsRoute
  '/deals': typeof DealsRoute
  '/flights': typeof FlightsRoute
  '/host': typeof HostRoute
  '/more': typeof MoreRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/stays': typeof StaysRoute
  '/support': typeof SupportRoute
  '/transfers': typeof TransfersRoute
  '/trips': typeof TripsRoute
  '/welcome': typeof WelcomeRoute
  '/activities/$slug': typeof ActivitiesSlugRoute
  '/book/$slug': typeof BookSlugRoute
  '/booking/$reference': typeof BookingReferenceRoute
  '/listing/$slug': typeof ListingSlugRoute
  '/order/$reference': typeof OrderReferenceRoute
  '/activities/': typeof ActivitiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/book-flight'
    | '/cars'
    | '/deals'
    | '/flights'
    | '/host'
    | '/more'
    | '/saved'
    | '/search'
    | '/stays'
    | '/support'
    | '/transfers'
    | '/trips'
    | '/welcome'
    | '/activities/$slug'
    | '/book/$slug'
    | '/booking/$reference'
    | '/listing/$slug'
    | '/order/$reference'
    | '/activities/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/book-flight'
    | '/cars'
    | '/deals'
    | '/flights'
    | '/host'
    | '/more'
    | '/saved'
    | '/search'
    | '/stays'
    | '/support'
    | '/transfers'
    | '/trips'
    | '/welcome'
    | '/activities/$slug'
    | '/book/$slug'
    | '/booking/$reference'
    | '/listing/$slug'
    | '/order/$reference'
    | '/activities'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/book-flight'
    | '/cars'
    | '/deals'
    | '/flights'
    | '/host'
    | '/more'
    | '/saved'
    | '/search'
    | '/stays'
    | '/support'
    | '/transfers'
    | '/trips'
    | '/welcome'
    | '/activities/$slug'
    | '/book/$slug'
    | '/booking/$reference'
    | '/listing/$slug'
    | '/order/$reference'
    | '/activities/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  BookFlightRoute: typeof BookFlightRoute
  CarsRoute: typeof CarsRoute
  DealsRoute: typeof DealsRoute
  FlightsRoute: typeof FlightsRoute
  HostRoute: typeof HostRoute
  MoreRoute: typeof MoreRoute
  SavedRoute: typeof SavedRoute
  SearchRoute: typeof SearchRoute
  StaysRoute: typeof StaysRoute
  SupportRoute: typeof SupportRoute
  TransfersRoute: typeof TransfersRoute
  TripsRoute: typeof TripsRoute
  WelcomeRoute: typeof WelcomeRoute
  ActivitiesSlugRoute: typeof ActivitiesSlugRoute
  BookSlugRoute: typeof BookSlugRoute
  BookingReferenceRoute: typeof BookingReferenceRoute
  ListingSlugRoute: typeof ListingSlugRoute
  OrderReferenceRoute: typeof OrderReferenceRoute
  ActivitiesIndexRoute: typeof ActivitiesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-flight': {
      id: '/book-flight'
      path: '/book-flight'
      fullPath: '/book-flight'
      preLoaderRoute: typeof BookFlightRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cars': {
      id: '/cars'
      path: '/cars'
      fullPath: '/cars'
      preLoaderRoute: typeof CarsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deals': {
      id: '/deals'
      path: '/deals'
      fullPath: '/deals'
      preLoaderRoute: typeof DealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flights': {
      id: '/flights'
      path: '/flights'
      fullPath: '/flights'
      preLoaderRoute: typeof FlightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host': {
      id: '/host'
      path: '/host'
      fullPath: '/host'
      preLoaderRoute: typeof HostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/more': {
      id: '/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof MoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stays': {
      id: '/stays'
      path: '/stays'
      fullPath: '/stays'
      preLoaderRoute: typeof StaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transfers': {
      id: '/transfers'
      path: '/transfers'
      fullPath: '/transfers'
      preLoaderRoute: typeof TransfersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips': {
      id: '/trips'
      path: '/trips'
      fullPath: '/trips'
      preLoaderRoute: typeof TripsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activities/': {
      id: '/activities/'
      path: '/activities'
      fullPath: '/activities/'
      preLoaderRoute: typeof ActivitiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activities/$slug': {
      id: '/activities/$slug'
      path: '/activities/$slug'
      fullPath: '/activities/$slug'
      preLoaderRoute: typeof ActivitiesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$slug': {
      id: '/book/$slug'
      path: '/book/$slug'
      fullPath: '/book/$slug'
      preLoaderRoute: typeof BookSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/$reference': {
      id: '/booking/$reference'
      path: '/booking/$reference'
      fullPath: '/booking/$reference'
      preLoaderRoute: typeof BookingReferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listing/$slug': {
      id: '/listing/$slug'
      path: '/listing/$slug'
      fullPath: '/listing/$slug'
      preLoaderRoute: typeof ListingSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/$reference': {
      id: '/order/$reference'
      path: '/order/$reference'
      fullPath: '/order/$reference'
      preLoaderRoute: typeof OrderReferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  BookFlightRoute: BookFlightRoute,
  CarsRoute: CarsRoute,
  DealsRoute: DealsRoute,
  FlightsRoute: FlightsRoute,
  HostRoute: HostRoute,
  MoreRoute: MoreRoute,
  SavedRoute: SavedRoute,
  SearchRoute: SearchRoute,
  StaysRoute: StaysRoute,
  SupportRoute: SupportRoute,
  TransfersRoute: TransfersRoute,
  TripsRoute: TripsRoute,
  WelcomeRoute: WelcomeRoute,
  ActivitiesSlugRoute: ActivitiesSlugRoute,
  BookSlugRoute: BookSlugRoute,
  BookingReferenceRoute: BookingReferenceRoute,
  ListingSlugRoute: ListingSlugRoute,
  OrderReferenceRoute: OrderReferenceRoute,
  ActivitiesIndexRoute: ActivitiesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
