/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DealsRouteImport } from './routes/deals'
import { Route as MoreRouteImport } from './routes/more'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as TripsRouteImport } from './routes/trips'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as BookSlugRouteImport } from './routes/book.$slug'
import { Route as BookingReferenceRouteImport } from './routes/booking.$reference'
import { Route as ListingSlugRouteImport } from './routes/listing.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DealsRoute = DealsRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => rootRouteImport,
} as any)
const MoreRoute = MoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsRoute = TripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const BookSlugRoute = BookSlugRouteImport.update({
  id: '/book/$slug',
  path: '/book/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingReferenceRoute = BookingReferenceRouteImport.update({
  id: '/booking/$reference',
  path: '/booking/$reference',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingSlugRoute = ListingSlugRouteImport.update({
  id: '/listing/$slug',
  path: '/listing/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/deals': typeof DealsRoute
  '/more': typeof MoreRoute
  '/saved': typeof SavedRoute
  '/trips': typeof TripsRoute
  '/welcome': typeof WelcomeRoute
  '/book/$slug': typeof BookSlugRoute
  '/booking/$reference': typeof BookingReferenceRoute
  '/listing/$slug': typeof ListingSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/deals': typeof DealsRoute
  '/more': typeof MoreRoute
  '/saved': typeof SavedRoute
  '/trips': typeof TripsRoute
  '/welcome': typeof WelcomeRoute
  '/book/$slug': typeof BookSlugRoute
  '/booking/$reference': typeof BookingReferenceRoute
  '/listing/$slug': typeof ListingSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/deals': typeof DealsRoute
  '/more': typeof MoreRoute
  '/saved': typeof SavedRoute
  '/trips': typeof TripsRoute
  '/welcome': typeof WelcomeRoute
  '/book/$slug': typeof BookSlugRoute
  '/booking/$reference': typeof BookingReferenceRoute
  '/listing/$slug': typeof ListingSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/deals'
    | '/more'
    | '/saved'
    | '/trips'
    | '/welcome'
    | '/book/$slug'
    | '/booking/$reference'
    | '/listing/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/deals'
    | '/more'
    | '/saved'
    | '/trips'
    | '/welcome'
    | '/book/$slug'
    | '/booking/$reference'
    | '/listing/$slug'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/deals'
    | '/more'
    | '/saved'
    | '/trips'
    | '/welcome'
    | '/book/$slug'
    | '/booking/$reference'
    | '/listing/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DealsRoute: typeof DealsRoute
  MoreRoute: typeof MoreRoute
  SavedRoute: typeof SavedRoute
  TripsRoute: typeof TripsRoute
  WelcomeRoute: typeof WelcomeRoute
  BookSlugRoute: typeof BookSlugRoute
  BookingReferenceRoute: typeof BookingReferenceRoute
  ListingSlugRoute: typeof ListingSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deals': {
      id: '/deals'
      path: '/deals'
      fullPath: '/deals'
      preLoaderRoute: typeof DealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/more': {
      id: '/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof MoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips': {
      id: '/trips'
      path: '/trips'
      fullPath: '/trips'
      preLoaderRoute: typeof TripsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$slug': {
      id: '/book/$slug'
      path: '/book/$slug'
      fullPath: '/book/$slug'
      preLoaderRoute: typeof BookSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/$reference': {
      id: '/booking/$reference'
      path: '/booking/$reference'
      fullPath: '/booking/$reference'
      preLoaderRoute: typeof BookingReferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listing/$slug': {
      id: '/listing/$slug'
      path: '/listing/$slug'
      fullPath: '/listing/$slug'
      preLoaderRoute: typeof ListingSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DealsRoute: DealsRoute,
  MoreRoute: MoreRoute,
  SavedRoute: SavedRoute,
  TripsRoute: TripsRoute,
  WelcomeRoute: WelcomeRoute,
  BookSlugRoute: BookSlugRoute,
  BookingReferenceRoute: BookingReferenceRoute,
  ListingSlugRoute: ListingSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
