// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wxpflbafjuvvzqmvoffy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind4cGZsYmFmanV2dnpxbXZvZmZ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODY5MTEzNzAsImV4cCI6MjEwMjQ4NzM3MH0.X3gDPatmllWpwS2O-QIIIYf45mKe6BWvQKj6pC84NZ8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});